<?php
/**
 * Example 5xx Server Error template for Chandler.
 *
 * @var bool $logged Whether the exception was successfully written to the log file.
 */
?>
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <style>
    body,h1,h2,h3{margin:0;}
    body{font-family:sans-serif;background-color:#cee3ef;}
    fieldset{border-color:#73716b;}
    legend{font-weight:900;background-color:#e7eff7;border:2px solid #e0e0e0;border-bottom:2px solid #949694;}
    h2,h3{color:#ce0000;}
    h2{margin-bottom:10px;}
    #header,#subheader_Server{color:#fff;padding:20px;}
    #header{background-color:#5a86b5;border-bottom:1px solid #4a6d8c;}
    #subheader_Server{background-color:#5a7da5;text-align:right;border-bottom: 1px solid #c6cfde;}
    .container{margin:20px;padding:10px;background-color:#fff;}
    </style>
    <title>Error 500</title>
</head>
<body>
    <div id="header">
        <h1>Server error</h1>
    </div>
    <div id="subheader_Server">
        libchandler
    </div>
    <div class="container">
        <fieldset>
            <legend>Error summary</legend>
            
            <h2>HTTP Error 500 - Internal Server Error</h2>
            <h3>An unexpected error occurred on the server.</h3>
            <?php if (!empty($logged)): ?>
                <p><small>The error was logged to file.</small></p>
            <?php else: ?>
                <p><small>The error could not be logged.</small></p>
            <?php endif; ?>
        </fieldset>
    </div>
</body>
</html>
